version: '3'

networks:
  lumen:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-lumen-barebone
    ports:
      - "8080:80"
    volumes:
      - /home/kripalsth/html/lumen-barebone:/var/www/html
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lumen

  php:
    build: ./server/php
    container_name: php-lumen-barebone
    ports:
      - "9000:9000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./server/php/php-fpm.ini:/usr/local/etc/php/conf.d/php-fpm.ini
      - ./server/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
      - /home/kripalsth/html/lumen-barebone:/var/www/html
      - /home/kripalsth/.composer:/root/.composer
    networks:
      - lumen

  mysql:
    image: mysql:5.7.22
    container_name: mysql-lumen-barebone
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen